### ISSUE TITLE
Orange Pie Zero cant handle this library

### ISSUE THREAD

**Issue by msaraac** [awslabs/aws-crt-python#253]
Device : Orange Pie Zero ( 512 MB Memory )

```
Collecting awsiotsdk
  Downloading https://files.pythonhosted.org/packages/ed/42/4ce086a53251bf4ee82764402ec63b3e60ea15d879c258e954f0283e1b44/awsiotsdk-1.5.8-py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 1.1MB/s
Collecting awscrt==0.10.8 (from awsiotsdk)
  Downloading https://files.pythonhosted.org/packages/19/07/1e06d8fa945399e535ceeae8e98428d57b9cedea269e61b9244cd90e2a64/awscrt-0.10.8.tar.gz (2.8MB)
    100% |████████████████████████████████| 2.9MB 5.6MB/s
Installing collected packages: awscrt, awsiotsdk
  Running setup.py install for awscrt ... \ssKilled
```

I tried increasing swap file, not worked.
I tried with both python3.8 and python3.7

pip installation logs
```
2021-03-22T09:57:45,707 Using pip 21.0.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
2021-03-22T09:57:45,718 Non-user install because site-packages writeable
2021-03-22T09:57:46,169 Created temporary directory: /tmp/pip-ephem-wheel-cache-b9nj58e8
2021-03-22T09:57:46,171 Created temporary directory: /tmp/pip-req-tracker-nzui7aj2
2021-03-22T09:57:46,172 Initialized build tracking at /tmp/pip-req-tracker-nzui7aj2
2021-03-22T09:57:46,172 Created build tracker: /tmp/pip-req-tracker-nzui7aj2
2021-03-22T09:57:46,173 Entered build tracker: /tmp/pip-req-tracker-nzui7aj2
2021-03-22T09:57:46,174 Created temporary directory: /tmp/pip-install-cdh8zab8
2021-03-22T09:57:46,223 1 location(s) to search for versions of awsiotsdk:
2021-03-22T09:57:46,223 * https://pypi.org/simple/awsiotsdk/
2021-03-22T09:57:46,224 Fetching project page and analyzing links: https://pypi.org/simple/awsiotsdk/
2021-03-22T09:57:46,226 Getting page https://pypi.org/simple/awsiotsdk/
2021-03-22T09:57:46,230 Found index url https://pypi.org/simple
2021-03-22T09:57:47,917   Found link https://files.pythonhosted.org/packages/38/04/fc6effef82ba8e7dec9c00d6ac903ad403e99b976450bfe658693a536507/awsiotsdk-0.2.4-py2.py3-none-any.whl#sha256=12508824840dfc660d96f6eb79be88cbed117777c0bb7b12f99307edf5ea0d79 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 0.2.42021-03-22T09:57:47,920   Found link https://files.pythonhosted.org/packages/f0/2d/0d6ebbf6234000f89944cd7c7b5436b9e1f8c3f96fa026238c6028edf365/awsiotsdk-0.2.4.tar.gz#sha256=79e0eb613f7d37a52a4836c82fae4acfe072079783da622da8764cd025064fc3 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 0.2.4
2021-03-22T09:57:47,923   Found link https://files.pythonhosted.org/packages/ed/3e/8a09697e120436452eafa014d27dd2dd5314cfc3ab9476c5531f6ad84740/awsiotsdk-0.2.9-py2.py3-none-any.whl#sha256=f441e460a53e43dc0830253c4c13cc7d734a6bd3a648976a48dd83437170c803 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 0.2.9
2021-03-22T09:57:47,925   Found link https://files.pythonhosted.org/packages/30/a2/1f0c8f653cb9ab65bcfaff087fd5930368262a38cab2278debd69f7ae92b/awsiotsdk-0.2.9.tar.gz#sha256=dee9f79ebca96a709fb72f0c276fbb3283620b5c833e77e39b10ee1fd7a77ea4 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 0.2.9
2021-03-22T09:57:47,927   Found link https://files.pythonhosted.org/packages/61/de/be6a018656c5157989d34e3b6c49c72a6a2acab95359f7a8f4f9b5f293eb/awsiotsdk-0.3.0-py2.py3-none-any.whl#sha256=3095270161410d756ee4337fd833a86c146aa12e0cd6b695f2223e46aa576271 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 0.3.0
2021-03-22T09:57:47,929   Found link https://files.pythonhosted.org/packages/3c/19/a43ecf40f9dc3c7e7b6d1c8794d3efb2a526c0e82dde3d877fd1e54a7fcd/awsiotsdk-0.3.0.tar.gz#sha256=b06815b58b5986487e77d2747757aab20cd54b88e24903077dc2f2e43f19221f (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 0.3.0
2021-03-22T09:57:47,932   Found link https://files.pythonhosted.org/packages/1b/9f/ec49b84500d684bf60501bed2a3abf56d067e01e915bb26ad9de240f2920/awsiotsdk-1.0.2-py2.py3-none-any.whl#sha256=daa5f1b8ea821f6a67cd79887e1e8402ba1d9e18217e595f87731f8d0ca78959 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.0.2
2021-03-22T09:57:47,934   Found link https://files.pythonhosted.org/packages/84/aa/18082eae2dde883b9156c68c0aa38ab25f16a7fb58e1fb25b9b27a891766/awsiotsdk-1.0.2.tar.gz#sha256=dc8f9b342159ccdea2aab15daae38afd470367f85e02174b9ee2a2e02c9b1796 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.0.2
2021-03-22T09:57:47,936   Found link https://files.pythonhosted.org/packages/12/90/192226e87048d6606ca6ac42b7844b025050af529f7089fc5ddfab17e7fc/awsiotsdk-1.0.3-py2.py3-none-any.whl#sha256=376430255e5a050cf08256a2d09f11b2a235913d6222d45b8a402ff20e6adc86 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.0.3
2021-03-22T09:57:47,938   Found link https://files.pythonhosted.org/packages/4b/0a/e47b83d280c592e297b507d0135200e7e2f8db4c4003d48c32ddb3eddfaf/awsiotsdk-1.0.3.tar.gz#sha256=69ca127c4234a6bec07481d72d375afdf64b9a4c74bbf68849e18517c962e838 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.0.3
2021-03-22T09:57:47,941   Found link https://files.pythonhosted.org/packages/cb/7c/b91125f0c603989a76c8ba5c2fda598a7b8b657730e5e1557c0b6dfc7dbe/awsiotsdk-1.0.5-py2.py3-none-any.whl#sha256=af17d349ea130c8bc2614b1b7a3c42f8461c4dfc96a6a4bf5270d9c2e1b1dab7 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.0.5
2021-03-22T09:57:47,943   Found link https://files.pythonhosted.org/packages/4a/1a/fb3d826493cef3889c329ee62e1231c69cb663c54e2410cd2b1952cee521/awsiotsdk-1.0.5.tar.gz#sha256=cf70212c37c59e2eb2635dff438d52c8c5dde0fb920c0e4ff5b269da062522fe (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.0.5
2021-03-22T09:57:47,945   Found link https://files.pythonhosted.org/packages/f9/c2/860d79771f1a576c8bfb5b2321a12bdc6396c8eafea5388977df2e942fe0/awsiotsdk-1.0.6-py2.py3-none-any.whl#sha256=dcf236493d8d5fb673086b34a4deeb21be5e1e5bc6340389fba3e1707572430b (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.0.6
2021-03-22T09:57:47,947   Found link https://files.pythonhosted.org/packages/41/30/8411889de6b77d01ecc470f9cfeb44d8ef0cdf647afd35463c56f2aab6a8/awsiotsdk-1.0.6.tar.gz#sha256=e59ac398fe65079e243a87c2390b4e82388fbe1cbc6893a8e1b0d8a0698a5428 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.0.6
2021-03-22T09:57:47,949   Found link https://files.pythonhosted.org/packages/95/36/5e510997e38b95ec3a9c0d5055b3e4cbde5143c387c446d08922e922a5a3/awsiotsdk-1.1.0-py2.py3-none-any.whl#sha256=c59cba07a76d3c87273ab2a36059e73b7d93b65d219c8ac44e052d8dbbce7b00 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.1.0
2021-03-22T09:57:47,951   Found link https://files.pythonhosted.org/packages/f7/40/cee9f2217b937ac61a7fb5344d489ad6b7bf806f780b65463ffb58ea075d/awsiotsdk-1.1.0.tar.gz#sha256=efec9362062cfe1094e63e4afb7e77e4394a6233cecaf31e3fcd2889a6eb784d (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.1.0
2021-03-22T09:57:47,954   Found link https://files.pythonhosted.org/packages/fc/35/df8f8796f0b689b422fff3304b32fca5f686fa8bff9e95e24b84389fdf53/awsiotsdk-1.2.0-py2.py3-none-any.whl#sha256=d84feaa04e42a6922b48081719b114166cd39cc28ebaced7d7828b0a12290412 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.2.0
2021-03-22T09:57:47,956   Found link https://files.pythonhosted.org/packages/9a/5e/a4e904f9fcbcb3eb1fed3c95f36de46fbc00a9f112a8fd8b20e16806ad83/awsiotsdk-1.2.0.tar.gz#sha256=1bdc97f8ee1f32fb904dbd71268dfd088190ece873ddf8a028211f17c6d1fce3 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.2.0
2021-03-22T09:57:47,958   Found link https://files.pythonhosted.org/packages/e7/b7/e8a31b63ec1c20c7a9f8155c7fdf3aea9af40a5e6d9cf060ceab8839b4ca/awsiotsdk-1.2.1-py2.py3-none-any.whl#sha256=257aed87b709e960d2c1da8484b35a467779a9cf4531af9f24b7952a4d4a22a6 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.2.1
2021-03-22T09:57:47,960   Found link https://files.pythonhosted.org/packages/e7/b2/5075d877a73040280f24ce08b0d9b0b41bc4eef396a04a92d013bedaf8ef/awsiotsdk-1.2.1.tar.gz#sha256=9d4321f0ca874ee1d39efc064b07d07150e045d85ae73ad26a69faa99a84aa05 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.2.1
2021-03-22T09:57:47,962   Found link https://files.pythonhosted.org/packages/40/83/caacc9991c3b08138f8a950581010e45472845ad545a712923fb7318a8d0/awsiotsdk-1.3.0-py2.py3-none-any.whl#sha256=d80ce6f2067cf9d700217b1b57ef520f3bf5d2c082fa19078e216d9a9e726655 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.3.0
2021-03-22T09:57:47,964   Found link https://files.pythonhosted.org/packages/c0/ee/5ef67d4888577e8630a05d15a754e690ce05f74e19ae4ea8451556c4bb74/awsiotsdk-1.3.0.tar.gz#sha256=8cf9365297bb8b85b8b7cafe0bb0c9720b4fb1996a07c4c0849269820b3ace18 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.3.0
2021-03-22T09:57:47,967   Found link https://files.pythonhosted.org/packages/c3/e6/975baec2f1109f8e3845ba328ccc8aedddf6e2453808f1fc991f0eac4bfd/awsiotsdk-1.3.1-py2.py3-none-any.whl#sha256=85574fcda25625dee856ea56e24df219f47b1593785b529728a0e7b3d175b820 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.3.1
2021-03-22T09:57:47,969   Found link https://files.pythonhosted.org/packages/b1/21/16ec62897f3e84fa7bddac43ca985bc60f015a1610c5ede6f888b84a0e77/awsiotsdk-1.3.1.tar.gz#sha256=f402c459aa683823a2825959b342e89294347b6d242212626045080f75f7a474 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.3.1
2021-03-22T09:57:47,971   Found link https://files.pythonhosted.org/packages/13/2a/42c5d6e253f0ea398b484e46b339722d2e45406c3b763a79753f62ab6c48/awsiotsdk-1.3.2-py2.py3-none-any.whl#sha256=94b09a936caef0bce8c92d4d5251e95cf052581092eb4b54458b720c753c2143 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.3.2
2021-03-22T09:57:47,973   Found link https://files.pythonhosted.org/packages/6a/e8/28c3261b1dc51b0892b2e128c304077e6967cd57d8bcdff582358439492d/awsiotsdk-1.3.2.tar.gz#sha256=2bac1042707cfe00643cdd0736f13e889ac591dd0d23372ac0fe2a220c78ce56 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.3.2
2021-03-22T09:57:47,976   Found link https://files.pythonhosted.org/packages/ee/b4/15c33e74ebbd2d12e6b701e4fd96875608de14ec39054b4b95de0a37e2ca/awsiotsdk-1.4.0-py2.py3-none-any.whl#sha256=bd6c19ce0a94a89d309d848928b86b5113dfafbd9c03a7390a690b853ef01652 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.4.0
2021-03-22T09:57:47,977   Found link https://files.pythonhosted.org/packages/27/3b/df340eaad7c349683fecd370aa2ca7f07fa0a126665b8f2e875e67e139dd/awsiotsdk-1.4.0.tar.gz#sha256=c631825d6dea0373fcc1b0359b5c06958e6a2406deac37d2ccc9435da7f43131 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=2.7), version: 1.4.0
2021-03-22T09:57:47,980   Found link https://files.pythonhosted.org/packages/ee/ea/0509111f382972ab2dfbe38568c2559a4267c6970813579bb2699608e47b/awsiotsdk-1.5.0-py2.py3-none-any.whl#sha256=e54ff07c2de8a51f98b5d2b8365493380e921b7ff450ebca6f7437d538a0ba37 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.0
2021-03-22T09:57:47,982   Found link https://files.pythonhosted.org/packages/02/b5/1dcb793025314ccdc330260327eaed41b7bc4d09e57ddda4f6aff4e6e810/awsiotsdk-1.5.0.tar.gz#sha256=32f5f1fd2692d14819c14a18c77cdf307c26ee10379dc8986221070fb1f7333c (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.0
2021-03-22T09:57:47,984   Found link https://files.pythonhosted.org/packages/66/4e/4a868f5e3096d4ec764d1b2990a52b393b03dce167741d19d35cc3cb1364/awsiotsdk-1.5.1-py3-none-any.whl#sha256=743268d7b5af1e04a2f49f45420fc887d8604f7586075dc40f08e93a47acb547 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.1
2021-03-22T09:57:47,986   Found link https://files.pythonhosted.org/packages/08/d4/428c7e8f1fc90c04a48725bebb1e89c5768ec4c7d11d5b40a7157be1b2d5/awsiotsdk-1.5.1.tar.gz#sha256=4ea6386fe5870ecbb0af46dccff30e30f22abe5bca255305bf35d00820a175d1 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.1
2021-03-22T09:57:47,988   Found link https://files.pythonhosted.org/packages/fe/38/c1a8322f4dcb1708bb61e00093489433a3aca05014b002fcbdb273c4aacc/awsiotsdk-1.5.2-py3-none-any.whl#sha256=767758da8a3012ed380ce0c6e23ab4f6503e276354b44151c4e78a7771dfdb6a (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.2
2021-03-22T09:57:47,990   Found link https://files.pythonhosted.org/packages/1b/aa/4ae15b1fcb6f00e45d008b5a579de0c55ebf6595731c4ea373332d8ed2a8/awsiotsdk-1.5.2.tar.gz#sha256=534127220dc444d889277550731a100147143b91e87bcaec452499b6e04294b2 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.2
2021-03-22T09:57:47,992   Found link https://files.pythonhosted.org/packages/7d/01/a0f0663ad948b1337490788d566421a2f7c1217cd759637590cc96563d5a/awsiotsdk-1.5.3-py3-none-any.whl#sha256=e3ef175323399deb69776823e5a52a2e620d1acf6aa3ae66fc87769e1602ba77 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.3
2021-03-22T09:57:47,994   Found link https://files.pythonhosted.org/packages/d9/b9/b10dda71182623fa0bfb5f99a5b20bfc624d9948e7c9f75d57d4faeb113a/awsiotsdk-1.5.3.tar.gz#sha256=a2f106e1066e2e46b998f918ccd3786f9464293f794474eae76886d1398cda96 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.3
2021-03-22T09:57:47,997   Found link https://files.pythonhosted.org/packages/35/68/8ead5545a2954ff423e19a08268a88a993f590fcf218e7c9d392898f4d87/awsiotsdk-1.5.4-py3-none-any.whl#sha256=1de77cb9ce36fb73b28d4a5ca9c1450b8d3acdd49c1ef834019bf09383176ad2 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.4
2021-03-22T09:57:48,000   Found link https://files.pythonhosted.org/packages/f5/ce/5557d3aef6f0f3aa7e7eeedf611117940fed9ab3fd62b412bf2db95102dc/awsiotsdk-1.5.4.tar.gz#sha256=3cfa63745387eb34c2081c6291aa9cac9549c22bb6b153fbd928d0d608d23d00 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.4
2021-03-22T09:57:48,002   Found link https://files.pythonhosted.org/packages/19/7c/9b7c3528db729b5c5b5b1f6f06f768eb489103c2ba0492544c955902638e/awsiotsdk-1.5.5-py3-none-any.whl#sha256=898d79dccff14ef6f88b37abf66f7004d1a7e6330dbe90bf6fc60c87794736a8 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.5
2021-03-22T09:57:48,004   Found link https://files.pythonhosted.org/packages/2e/46/6f05dd90ace5bbd7a1e47285edc8d7bac63d129fa984707af96b8cc2fff1/awsiotsdk-1.5.5.tar.gz#sha256=46c74af61c38f5be6cfc237d94a3f83aabb55995f299b4c1cf21403bef5555e4 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.5
2021-03-22T09:57:48,006   Found link https://files.pythonhosted.org/packages/55/d1/239722d8cea8e3a1c4a822a7f90e09961e1863a75e64a2227ac96653b16d/awsiotsdk-1.5.6-py3-none-any.whl#sha256=66740de537c8c7c20b09b20c2a6a93fc1d6362a45a661bf30163bc2cdb85fa28 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.6
2021-03-22T09:57:48,008   Found link https://files.pythonhosted.org/packages/35/ad/d6cc3ea0e33df4e0268a22eb031a4975131cf40bdde50c1076e1a33f7e18/awsiotsdk-1.5.6.tar.gz#sha256=69db70678d773abbbd37389a829f59d5c3ece6f60389f2eebcef9b290973dcf8 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.6
2021-03-22T09:57:48,011   Found link https://files.pythonhosted.org/packages/4b/9a/c861fd8cf3ed08e510560348e82fe263b97305a6f678d202863f1766791d/awsiotsdk-1.5.7-py3-none-any.whl#sha256=d2b74c5ee7d398aa8b0fc16a63e4d4550497bbd6bc05ef74417fd4737cbcca06 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.7
2021-03-22T09:57:48,013   Found link https://files.pythonhosted.org/packages/b5/b9/687d2bf0d9b9d87617535e5581afcf5aaf08bfc8b236b9c8885536b7f09b/awsiotsdk-1.5.7.tar.gz#sha256=fe9a699cecfe41ee8993c2f3fa9dfa5f0cc89e3976fafac85a8f9d7c23a3890a (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.7
2021-03-22T09:57:48,015   Found link https://files.pythonhosted.org/packages/ed/42/4ce086a53251bf4ee82764402ec63b3e60ea15d879c258e954f0283e1b44/awsiotsdk-1.5.8-py3-none-any.whl#sha256=c03e8f355304bca8222b449b1c018b90fb73892486daa26ce7742fadf54d0ed5 (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.8
2021-03-22T09:57:48,017   Found link https://files.pythonhosted.org/packages/58/b6/2403b2daf0898ca71c881ade7a26ebe481e5d0f22e863c43c459243442c2/awsiotsdk-1.5.8.tar.gz#sha256=fd8b5c1aa3d77c5f80c8b20d10f5a94e357b60b2e715be3e740e8c2e8b78cf1b (from https://pypi.org/simple/awsiotsdk/) (requires-python:>=3.5), version: 1.5.8
2021-03-22T09:57:48,027 Given no hashes to check 46 links for project 'awsiotsdk': discarding no candidates
2021-03-22T09:57:48,235 Collecting awsiotsdk
2021-03-22T09:57:48,238   Created temporary directory: /tmp/pip-unpack-cjjtkkl2
2021-03-22T09:57:48,658   Downloading awsiotsdk-1.5.7-py3-none-any.whl (38 kB)
2021-03-22T09:57:48,712   Added awsiotsdk from https://files.pythonhosted.org/packages/4b/9a/c861fd8cf3ed08e510560348e82fe263b97305a6f678d202863f1766791d/awsiotsdk-1.5.7-py3-none-any.whl#sha256=d2b74c5ee7d398aa8b0fc16a63e4d4550497bbd6bc05ef74417fd4737cbcca06 to build tracker '/tmp/pip-req-tracker-nzui7aj2'
2021-03-22T09:57:48,713   Removed awsiotsdk from https://files.pythonhosted.org/packages/4b/9a/c861fd8cf3ed08e510560348e82fe263b97305a6f678d202863f1766791d/awsiotsdk-1.5.7-py3-none-any.whl#sha256=d2b74c5ee7d398aa8b0fc16a63e4d4550497bbd6bc05ef74417fd4737cbcca06 from build tracker '/tmp/pip-req-tracker-nzui7aj2'
2021-03-22T09:57:48,740 1 location(s) to search for versions of awscrt:
2021-03-22T09:57:48,740 * https://pypi.org/simple/awscrt/
2021-03-22T09:57:48,741 Fetching project page and analyzing links: https://pypi.org/simple/awscrt/
2021-03-22T09:57:48,742 Getting page https://pypi.org/simple/awscrt/
2021-03-22T09:57:48,744 Found index url https://pypi.org/simple
2021-03-22T09:57:50,087 ERROR: Operation cancelled by user
2021-03-22T09:57:50,089 Exception information:
2021-03-22T09:57:50,089 Traceback (most recent call last):
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
2021-03-22T09:57:50,089     crit = self.state.criteria[name]
2021-03-22T09:57:50,089 KeyError: 'awscrt'
2021-03-22T09:57:50,089
2021-03-22T09:57:50,089 During handling of the above exception, another exception occurred:
2021-03-22T09:57:50,089
2021-03-22T09:57:50,089 Traceback (most recent call last):
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 189, in _main
2021-03-22T09:57:50,089     status = self.run(options, args)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
2021-03-22T09:57:50,089     return func(self, options, args)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 317, in run
2021-03-22T09:57:50,089     reqs, check_supported_wheels=not options.target_dir
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
2021-03-22T09:57:50,089     requirements, max_rounds=try_to_avoid_resolution_too_deep,
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
2021-03-22T09:57:50,089     state = resolution.resolve(requirements, max_rounds=max_rounds)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 347, in resolve
2021-03-22T09:57:50,089     failure_causes = self._attempt_to_pin_criterion(name, criterion)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
2021-03-22T09:57:50,089     criteria = self._get_criteria_to_update(candidate)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 199, in _get_criteria_to_update
2021-03-22T09:57:50,089     name, crit = self._merge_into_criterion(r, parent=candidate)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
2021-03-22T09:57:50,089     crit = Criterion.from_requirement(self._p, requirement, parent)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
2021-03-22T09:57:50,089     if not cands:
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
2021-03-22T09:57:50,089     return bool(self._sequence)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
2021-03-22T09:57:50,089     return any(self)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 35, in _iter_built
2021-03-22T09:57:50,089     for version, func in infos:
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 223, in iter_index_candidate_infos
2021-03-22T09:57:50,089     hashes=hashes,
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/package_finder.py", line 872, in find_best_candidate
2021-03-22T09:57:50,089     candidates = self.find_all_candidates(project_name)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/package_finder.py", line 816, in find_all_candidates
2021-03-22T09:57:50,089     project_url, link_evaluator=link_evaluator,
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/package_finder.py", line 783, in process_project_url
2021-03-22T09:57:50,089     page_links = list(parse_links(html_page))
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/collector.py", line 323, in wrapper_wrapper
2021-03-22T09:57:50,089     return list(fn(page))
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_internal/index/collector.py", line 337, in parse_links
2021-03-22T09:57:50,089     namespaceHTMLElements=False,
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/html5lib/html5parser.py", line 46, in parse
2021-03-22T09:57:50,089     return p.parse(doc, **kwargs)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/html5lib/html5parser.py", line 284, in parse
2021-03-22T09:57:50,089     self._parse(stream, False, None, *args, **kwargs)
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/html5lib/html5parser.py", line 133, in _parse
2021-03-22T09:57:50,089     self.mainLoop()
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/html5lib/html5parser.py", line 204, in mainLoop
2021-03-22T09:57:50,089     for token in self.tokenizer:
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/html5lib/_tokenizer.py", line 65, in __iter__
2021-03-22T09:57:50,089     while self.state():
2021-03-22T09:57:50,089   File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/html5lib/_tokenizer.py", line 930, in attributeNameState
2021-03-22T09:57:50,089     self.currentToken["data"][-1][0].translate(asciiUpper2Lower))
2021-03-22T09:57:50,089 KeyboardInterrupt
2021-03-22T09:57:50,219 Removed build tracker: '/tmp/pip-req-tracker-nzui7aj2'
2021-03-22T09:57:58,273 Using pip 21.0.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
2021-03-22T09:57:58,283 Non-user install because site-packages writeable
2021-03-22T09:57:58,722 Created temporary directory: /tmp/pip-ephem-wheel-cache-tc3je3wz
2021-03-22T09:57:58,724 Created temporary directory: /tmp/pip-req-tracker-kdasia2h
2021-03-22T09:57:58,725 Initialized build tracking at /tmp/pip-req-tracker-kdasia2h
2021-03-22T09:57:58,726 Created build tracker: /tmp/pip-req-tracker-kdasia2h
2021-03-22T09:57:58,726 Entered build tracker: /tmp/pip-req-tracker-kdasia2h
2021-03-22T09:57:58,727 Created temporary directory: /tmp/pip-install-zhh7bqmw
2021-03-22T09:57:58,777 1 location(s) to search for versions of awsiotsdk:
2021-03-22T09:57:58,777 * https://pypi.org/simple/awsiotsdk/
2021-03-22T09:57:58,778 Fetching project page and analyzing links: https://pypi.org/simple/awsiotsdk/
2021-03-22T09:57:58,779 Getting page https://pypi.org/simple/awsiotsdk/
2021-03-22T09:57:58,784 Found index url https://pypi.org/simple
2021-03-22T09:57:59,355   Found link https://files.pythonhosted.org/packages/38/04/fc6effef82ba8e7dec9c00d6ac903ad403e99b976450bfe658693a536507/awsiotsdk-0.2.4-py2.py3-none-any.whl#sha256=12508824840dfc660d96f6eb79be88cbed117777c0bb7b12f99307edf5ea0d79 (from https
```

**Comment by graebm** [comment]
This might be fixed in version [0.11.8](https://github.com/awslabs/aws-crt-python/releases/tag/v0.11.8)
We limited the parallelism during builds
My Raspberry Pi 3B+ was also dying.

**Comment by graebm** [comment]
I can't figure out the exact ARM variant used by Orange Pi Zero...
What do you see when you run the following in the python3 interpreter?
```
>>> import distutils.util
>>> distutils.util.get_platform()
```

If you see `linux-armv7l` you could configure python to consult [piwheels.org](https://www.piwheels.org/) and just grab precompiled wheels from there.

Please share the platform if that doesn't work. I'm curious if it's a platform supported by pypi.org

**Comment by msaraac** [comment]
Thanks that works for me
