### ISSUE TITLE
SAM: Incompatible with lambda python 3.8

### ISSUE THREAD

**Issue by BrnoPCmaniak** [awslabs/aws-crt-python#291]
I have a basic sam template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  greengrass_terra

  Sample SAM Template for greengrass_terra

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  scd30CWReporterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: scd30CWReporter/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  scd30CWReporterFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt scd30CWReporterFunction.Arn
  scd30CWReporterFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt scd30CWReporterFunction.Arn

```

with following `requirements.txt`

```
awsiotsdk
```

When I try to package the lambda locally with `sam build --debug`:

```
$ sam build --debug
2021-05-21 17:44:03,211 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-05-21 17:44:03,211 | Using config file: samconfig.toml, config environment: default
2021-05-21 17:44:03,211 | Expand command line arguments to:
2021-05-21 17:44:03,211 | --template_file=/home/fdobrovo/ws/my/greengrass/greengrass_terra/template.yaml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2021-05-21 17:44:03,421 | 'build' command is called
2021-05-21 17:44:03,424 | No Parameters detected in the template
2021-05-21 17:44:03,444 | 1 stacks found in the template
2021-05-21 17:44:03,444 | No Parameters detected in the template
2021-05-21 17:44:03,461 | 1 resources found in the stack 
2021-05-21 17:44:03,461 | No Parameters detected in the template
2021-05-21 17:44:03,478 | Found Serverless function with name='scd30CWReporterFunction' and CodeUri='scd30CWReporter/'
2021-05-21 17:44:03,478 | --base-dir is not presented, adjusting uri scd30CWReporter/ relative to /home/fdobrovo/ws/my/greengrass/greengrass_terra/template.yaml
2021-05-21 17:44:03,478 | No Parameters detected in the template
2021-05-21 17:44:03,495 | Instantiating build definitions
2021-05-21 17:44:03,497 | Same function build definition found, adding function (Previous: BuildDefinition(python3.8, /home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter, Zip, , 0f6f69db-c824-4697-a081-c6e893a56484, {}, {}, []), Current: BuildDefinition(python3.8, /home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter, Zip, , 584c2518-6919-4d8a-9c37-ff3bda0a0230, {}, {}, []), Function: Function(name='scd30CWReporterFunction', functionname='scd30CWReporterFunction', runtime='python3.8', memory=None, timeout=3, handler='app.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter', environment=None, rolearn=None, layers=[], events=None, metadata=None, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-05-21 17:44:03,498 | Building codeuri: /home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter runtime: python3.8 metadata: {} functions: ['scd30CWReporterFunction']
2021-05-21 17:44:03,498 | Building to following folder /home/fdobrovo/ws/my/greengrass/greengrass_terra/.aws-sam/build/scd30CWReporterFunction
2021-05-21 17:44:03,498 | Loading workflow module 'aws_lambda_builders.workflows'
2021-05-21 17:44:03,500 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-05-21 17:44:03,501 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-05-21 17:44:03,502 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2021-05-21 17:44:03,503 | Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2021-05-21 17:44:03,504 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2021-05-21 17:44:03,505 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2021-05-21 17:44:03,506 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2021-05-21 17:44:03,507 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2021-05-21 17:44:03,508 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-05-21 17:44:03,508 | Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-05-21 17:44:03,529 | Running workflow 'PythonPipBuilder'
2021-05-21 17:44:03,529 | Running PythonPipBuilder:ResolveDependencies
2021-05-21 17:44:03,551 | calling pip download -r /home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter/requirements.txt --dest /tmp/tmpvydt4_01
2021-05-21 17:44:04,791 | Full dependency closure: {awsiotsdk==1.5.17(wheel), awscrt==0.11.20(wheel)}
2021-05-21 17:44:04,791 | initial compatible: {awsiotsdk==1.5.17(wheel)}
2021-05-21 17:44:04,791 | initial incompatible: {awscrt==0.11.20(wheel)}
2021-05-21 17:44:04,791 | Downloading missing wheels: {awscrt==0.11.20(wheel)}
2021-05-21 17:44:04,791 | calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/tmpvydt4_01 awscrt==0.11.20
2021-05-21 17:44:05,842 | compatible wheels after second download pass: {awsiotsdk==1.5.17(wheel)}
2021-05-21 17:44:05,842 | Build missing wheels from sdists (C compiling True): set()
2021-05-21 17:44:05,842 | compatible after building wheels (no C compiling): {awsiotsdk==1.5.17(wheel)}
2021-05-21 17:44:05,842 | Build missing wheels from sdists (C compiling False): set()
2021-05-21 17:44:05,842 | compatible after building wheels (C compiling): {awsiotsdk==1.5.17(wheel)}
2021-05-21 17:44:05,842 | Final compatible: {awsiotsdk==1.5.17(wheel)}
2021-05-21 17:44:05,842 | Final incompatible: {awscrt==0.11.20(wheel)}
2021-05-21 17:44:05,842 | Final missing wheels: {awscrt==0.11.20(wheel)}
2021-05-21 17:44:05,846 | PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/home/fdobrovo/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/home/fdobrovo/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/home/fdobrovo/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {awscrt==0.11.20(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fdobrovo/.local/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/home/fdobrovo/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {awscrt==0.11.20(wheel)}

Build Failed
2021-05-21 17:44:05,848 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'cce8e803-afa1-4cc3-8866-10aeb2e6cba8', 'installationId': 'b360f94c-bf08-4fee-ba22-aef38589a66c', 'sessionId': 'c263f797-df77-4c53-866c-495167f6b384', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.7', 'samcliVersion': '1.23.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 2635, 'exitReason': 'WorkflowFailedError', 'exitCode': 1}}]}
2021-05-21 17:44:06,520 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {awscrt==0.11.20(wheel)}

```

And using docker container:

```
$ sam build --debug --use-container
2021-05-21 17:40:49,803 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-05-21 17:40:49,803 | Using config file: samconfig.toml, config environment: default
2021-05-21 17:40:49,803 | Expand command line arguments to:
2021-05-21 17:40:49,803 | --template_file=/home/fdobrovo/ws/my/greengrass/greengrass_terra/template.yaml --use_container --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2021-05-21 17:40:50,015 | 'build' command is called
2021-05-21 17:40:50,015 | Starting Build inside a container
2021-05-21 17:40:50,018 | No Parameters detected in the template
2021-05-21 17:40:50,036 | 1 stacks found in the template
2021-05-21 17:40:50,037 | No Parameters detected in the template
2021-05-21 17:40:50,055 | 1 resources found in the stack 
2021-05-21 17:40:50,055 | No Parameters detected in the template
2021-05-21 17:40:50,072 | Found Serverless function with name='scd30CWReporterFunction' and CodeUri='scd30CWReporter/'
2021-05-21 17:40:50,072 | --base-dir is not presented, adjusting uri scd30CWReporter/ relative to /home/fdobrovo/ws/my/greengrass/greengrass_terra/template.yaml
2021-05-21 17:40:50,072 | No Parameters detected in the template
2021-05-21 17:40:50,090 | Instantiating build definitions
2021-05-21 17:40:50,092 | Same function build definition found, adding function (Previous: BuildDefinition(python3.8, /home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter, Zip, , 0f6f69db-c824-4697-a081-c6e893a56484, {}, {}, []), Current: BuildDefinition(python3.8, /home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter, Zip, , b6560917-5dbb-4549-a343-7c71eea9c9c8, {}, {}, []), Function: Function(name='scd30CWReporterFunction', functionname='scd30CWReporterFunction', runtime='python3.8', memory=None, timeout=3, handler='app.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter', environment=None, rolearn=None, layers=[], events=None, metadata=None, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-05-21 17:40:50,093 | Building codeuri: /home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter runtime: python3.8 metadata: {} functions: ['scd30CWReporterFunction']
2021-05-21 17:40:50,093 | Building to following folder /home/fdobrovo/ws/my/greengrass/greengrass_terra/.aws-sam/build/scd30CWReporterFunction

Fetching public.ecr.aws/sam/build-python3.8:latest Docker container image......
2021-05-21 17:40:51,682 | Mounting /home/fdobrovo/ws/my/greengrass/greengrass_terra/scd30CWReporter as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {awscrt==0.11.20(wheel), awsiotsdk==1.5.17(wheel)}
initial compatible: {awsiotsdk==1.5.17(wheel)}
initial incompatible: {awscrt==0.11.20(wheel)}
Downloading missing wheels: {awscrt==0.11.20(wheel)}
calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/samcli/scratch awscrt==0.11.20
compatible wheels after second download pass: {awsiotsdk==1.5.17(wheel)}
Build missing wheels from sdists (C compiling True): set()
compatible after building wheels (no C compiling): {awsiotsdk==1.5.17(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {awsiotsdk==1.5.17(wheel)}
Final compatible: {awsiotsdk==1.5.17(wheel)}
Final incompatible: {awscrt==0.11.20(wheel)}
Final missing wheels: {awscrt==0.11.20(wheel)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {awscrt==0.11.20(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {awscrt==0.11.20(wheel)}
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {awscrt==0.11.20(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {awscrt==0.11.20(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/__main__.py", line 117, in main
    builder.build(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {awscrt==0.11.20(wheel)}
2021-05-21 17:40:54,943 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {awscrt==0.11.20(wheel)}"}}

Build Failed
2021-05-21 17:40:55,116 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '2f5b704d-72b6-4c06-a16f-54b54c03f0f8', 'installationId': 'b360f94c-bf08-4fee-ba22-aef38589a66c', 'sessionId': '21107f18-6d19-496f-8933-630890527262', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.7', 'samcliVersion': '1.23.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 5312, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1}}]}
2021-05-21 17:40:55,810 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {awscrt==0.11.20(wheel)}
```

The same happens when I try the python3.7 env.

**Comment by BrnoPCmaniak** [comment]
This works fine when I rollback to awsiotsdk `1.5.16` which uses awscrt `0.11.19`

**Comment by jmklix** [comment]
Are you still running into problems while using the latest version of this sdk?

**Comment by yasminetalby** [comment]
Hello,

Thank you very much for your submission.
As there was no update, I am going to close this issue.

If you need any help or support you can open a new issue in the repositories.

Thank you very much for your time and contribution.
Sincerely,

Yasmine
