### ISSUE TITLE
getting `AWS_ERROR_MQTT_UNEXPECTED_HANGUP` running mqtt_test

### ISSUE THREAD

**Issue by tipu** [awslabs/aws-crt-python#340]
running the `mqtt_test.py` provided in the repo with the required arguments yields a `awscrt.exceptions.AwsCrtError: AWS_ERROR_MQTT_UNEXPECTED_HANGUP: The connection was closed unexpectedly.`

```
python mqtt_test.py --endpoint xxx-ats.iot.us-west-2.amazonaws.com 
                                 --cert ./certificate.pem.crt 
                                 --key ./private.pem.key
```

the output (which needed to be curtailed) is 

```
[TRACE] [2022-03-17T00:57:29Z] [00007f7f624bd700] [event-loop] - id=0x208a900: cancelling task 0x7f7f540013d0
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f624bd700] [task-scheduler] - id=0x7f7f540013d0: Running mqtt_connack_timeout task with <Canceled> status
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f624bd700] [channel-bootstrap] - id=0x20beb40: channel 0x7f7f54002890 shutdown with error 0.
[TRACE] [2022-03-17T00:57:29Z] [00007f7f624bd700] [mqtt-client] - id=0x20c4cf0: Channel has been shutdown with error code 0
[TRACE] [2022-03-17T00:57:29Z] [00007f7f624bd700] [mqtt-client] - id=0x20c4cf0: Discard ongoing requests and pending requests when a clean session connection lost.
[TRACE] [2022-03-17T00:57:29Z] [00007f7f624bd700] [mqtt-client] - id=0x20c4cf0: current state is 0
[TRACE] [2022-03-17T00:57:29Z] [00007f7f624bd700] [mqtt-client] - id=0x20c4cf0: slot is removed successfully
[TRACE] [2022-03-17T00:57:29Z] [00007f7f624bd700] [mqtt-client] - id=0x20c4cf0: Initial connection attempt failed, calling callback
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f624bd700] [channel] - id=0x7f7f54002890: destroying channel.
Traceback (most recent call last):
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f624bd700] [channel-bootstrap] - id=0x20beb40: releasing bootstrap reference
[TRACE] [2022-03-17T00:57:29Z] [00007f7f624bd700] [event-loop] - id=0x208a900: detected more scheduled tasks with the next occurring at 4761876245, using timeout of 4761.
[TRACE] [2022-03-17T00:57:29Z] [00007f7f624bd700] [event-loop] - id=0x208a900: waiting for a maximum of 4761 ms
  File "mqtt_test.py", line 99, in <module>
    connect_results = mqtt_connection.connect().result(TIMEOUT)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AWS_ERROR_MQTT_UNEXPECTED_HANGUP: The connection was closed unexpectedly.
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [mqtt-client] - id=0x20c4cf0: user called disconnect.
[ERROR] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [mqtt-client] - id=0x20c4cf0: Connection is not open, and may not be closed
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [mqtt-client] - id=0x20c4cf0: Last refcount on connection has been released, start destroying the connection.
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [mqtt-client] - id=0x20c4cf0: Destroying connection
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [mqtt-topic-tree] - tree=0x20c4f58: Cleaning up topic tree
[TRACE] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [mqtt-topic-tree] - node=0x20d05f0: Destroying topic tree node
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [mqtt-client] - client=0x2196d80: Cleaning up MQTT client
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [channel-bootstrap] - id=0x20beb40: releasing bootstrap reference
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [channel-bootstrap] - id=0x20beb40: releasing bootstrap reference
[DEBUG] [2022-03-17T00:57:29Z] [00007f7f63ab9740] [channel-bootstrap] - id=0x20beb40: destroying
```
any suggestions as to why this might be happening?

**Comment by bretambrose** [comment]
The logs start too late to see what's going on here (ie what state the client was in at the time of disconnect).  The error indicates the server closed the socket or the connection was otherwise lost based on something remote, and there are many reasons that could be behind it.  Unfortunately, the client has no insight into those reasons since the broker just closes the socket when it encounters a condition it doesn't like.

If you're never actually successfully connecting, then it might be a permissions issue (policy associated with your cert), cert issue (disabled, not registered), or something else.  A larger log snippet would help diagnose.

**Comment by bretambrose** [comment]
Closing absent further information
