### ISSUE TITLE
awscrt.exceptions.AwsCrtError: AWS_IO_DNS_INVALID_NAME: Host name was invalid for dns resolution

### ISSUE THREAD

**Issue by DeboBurro** [awslabs/aws-crt-python#377]
I created a `release-downloader` component based on the [example code](https://github.com/aws/aws-iot-device-sdk-python-v2/blob/main/samples/shadow.py). 
But at somepoint this morning, it showed `awscrt.exceptions.AwsCrtError: AWS_IO_DNS_INVALID_NAME: Host name was invalid for dns resolution` and the component doesn't respond anymore.

```
Username@Hostname:~$ sudo cat /greengrass/v2/logs/release-downloader.log
2022-07-25T12:31:18.446Z [INFO] (Copier) release-downloader: Run script exited. {exitCode=143, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:31:18.528Z [INFO] (pool-2-thread-24) release-downloader: shell-runner-start. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=STARTING, command=["/usr/bin/python3 /greengrass/v2/packages/artifacts-unarchived/release-download..."]}
2022-07-25T12:31:18.735Z [INFO] (Copier) release-downloader: Run script exited. {exitCode=143, serviceName=release-downloader, currentState=FINISHED}
2022-07-25T12:32:29.827Z [INFO] (pool-2-thread-16) release-downloader: shell-runner-start. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=STARTING, command=["/usr/bin/python3 /greengrass/v2/packages/artifacts-unarchived/release-download..."]}
2022-07-25T12:32:30.377Z [WARN] (Copier) release-downloader: stderr. 2022-07-25 08:32:30 INFO     Connecting to a3fdzwcty0l68t-ats.iot.us-west-2.amazonaws.com with client ID 'test-fcf78bf3-e379-4461-9453-1c84bf81547d'.... {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.382Z [WARN] (Copier) release-downloader: stderr. Traceback (most recent call last):. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.382Z [WARN] (Copier) release-downloader: stderr. File "/greengrass/v2/packages/artifacts-unarchived/release-downloader/1.0.1/release-downloader/release_downloader.py", line 567, in <module>. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.383Z [WARN] (Copier) release-downloader: stderr. connected_future.result(). {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.383Z [WARN] (Copier) release-downloader: stderr. File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.383Z [WARN] (Copier) release-downloader: stderr. return self.__get_result(). {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.383Z [WARN] (Copier) release-downloader: stderr. File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.383Z [WARN] (Copier) release-downloader: stderr. raise self._exception. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.383Z [WARN] (Copier) release-downloader: stderr. awscrt.exceptions.AwsCrtError: AWS_IO_DNS_INVALID_NAME: Host name was invalid for dns resolution.. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.395Z [INFO] (Copier) release-downloader: Run script exited. {exitCode=1, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.398Z [INFO] (pool-2-thread-19) release-downloader: shell-runner-start. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=STARTING, command=["/usr/bin/python3 /greengrass/v2/packages/artifacts-unarchived/release-download..."]}
2022-07-25T12:32:30.602Z [WARN] (Copier) release-downloader: stderr. 2022-07-25 08:32:30 INFO     Connecting to a3fdabcty0l71o-ats.iot.us-west-2.amazonaws.com with client ID 'test-b8fdc939-a96b-417e-9558-72d44a30623a'.... {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.605Z [WARN] (Copier) release-downloader: stderr. Traceback (most recent call last):. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.605Z [WARN] (Copier) release-downloader: stderr. File "/greengrass/v2/packages/artifacts-unarchived/release-downloader/1.0.1/release-downloader/release_downloader.py", line 567, in <module>. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.605Z [WARN] (Copier) release-downloader: stderr. connected_future.result(). {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.605Z [WARN] (Copier) release-downloader: stderr. File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.605Z [WARN] (Copier) release-downloader: stderr. return self.__get_result(). {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.605Z [WARN] (Copier) release-downloader: stderr. File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.605Z [WARN] (Copier) release-downloader: stderr. raise self._exception. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.605Z [WARN] (Copier) release-downloader: stderr. awscrt.exceptions.AwsCrtError: AWS_IO_DNS_INVALID_NAME: Host name was invalid for dns resolution.. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.616Z [INFO] (Copier) release-downloader: Run script exited. {exitCode=1, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.618Z [INFO] (pool-2-thread-19) release-downloader: shell-runner-start. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=STARTING, command=["/usr/bin/python3 /greengrass/v2/packages/artifacts-unarchived/release-download..."]}
2022-07-25T12:32:30.820Z [WARN] (Copier) release-downloader: stderr. 2022-07-25 08:32:30 INFO     Connecting to a3fdzwcty0l68t-ats.iot.us-west-2.amazonaws.com with client ID 'test-dbebe4bf-f995-4548-8822-3b19dfb91967'.... {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.823Z [WARN] (Copier) release-downloader: stderr. Traceback (most recent call last):. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.823Z [WARN] (Copier) release-downloader: stderr. File "/greengrass/v2/packages/artifacts-unarchived/release-downloader/1.0.1/release-downloader/release_downloader.py", line 567, in <module>. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.823Z [WARN] (Copier) release-downloader: stderr. connected_future.result(). {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.823Z [WARN] (Copier) release-downloader: stderr. File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.823Z [WARN] (Copier) release-downloader: stderr. return self.__get_result(). {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.823Z [WARN] (Copier) release-downloader: stderr. File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.823Z [WARN] (Copier) release-downloader: stderr. raise self._exception. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.823Z [WARN] (Copier) release-downloader: stderr. awscrt.exceptions.AwsCrtError: AWS_IO_DNS_INVALID_NAME: Host name was invalid for dns resolution.. {scriptName=services.release-downloader.lifecycle.Run.Script, serviceName=release-downloader, currentState=RUNNING}
2022-07-25T12:32:30.834Z [INFO] (Copier) release-downloader: Run script exited. {exitCode=1, serviceName=release-downloader, currentState=RUNNING}

```

**Comment by bretambrose** [comment]
Debug-level CRT logs would be the best shot at diagnosing this.  You should be able to enable them and target a writable space (like /tmp) from the component's permission-perspective.

**Comment by bretambrose** [comment]
Closing absent further information
