### ISSUE TITLE
Error when running the package aws-iot-device-python-v2 sample pubsub.py

### ISSUE THREAD

**Issue by jingshangwa** [awslabs/aws-crt-python#463]
Installed python version is 3.7.5. After following the installation guide of aws-iot-device-python-v2, which installed awscrt-0.16.13 awsiotsdk-1.12.6, try the sample code pubsub.py and resulted in the follow errors:

$ python3 aws-iot-device-sdk-python-v2/samples/pubsub.py --endpoint a19bnp1nufkk18-ats.iot.ap-southeast-1.amazonaws.com --ca_file /home/student/Downloads/root-CA.crt --cert /home/student/Downloads/ubuntu_test.cert.pem --key /home/student/Downloads/ubuntu_test.private.key --client_id basicPubSub --topic sdk/test/python --count 0

Traceback (most recent call last):
  File "aws-iot-device-sdk-python-v2/samples/pubsub.py", line 73, in <module>
    mqtt_connection = cmdUtils.build_mqtt_connection(on_connection_interrupted, on_connection_resumed)
  File "/home/student/Downloads/aws-iot-device-sdk-python-v2/samples/utils/command_line_utils.py", line 289, in build_mqtt_connection
    return self.build_direct_mqtt_connection(on_connection_interrupted, on_connection_resumed)
  File "/home/student/Downloads/aws-iot-device-sdk-python-v2/samples/utils/command_line_utils.py", line 282, in build_direct_mqtt_connection
    http_proxy_options=proxy_options)
  File "/home/student/.local/lib/python3.7/site-packages/awsiot/mqtt_connection_builder.py", line 251, in mtls_from_path
    return _builder(tls_ctx_options, **kwargs)
  File "/home/student/.local/lib/python3.7/site-packages/awsiot/mqtt_connection_builder.py", line 209, in _builder
    tls_ctx = awscrt.io.ClientTlsContext(tls_ctx_options)
  File "/home/student/.local/lib/python3.7/site-packages/awscrt/io.py", line 614, in __init__
    options._windows_cert_store_path,
RuntimeError: 34 (AWS_ERROR_INVALID_ARGUMENT): An invalid argument was passed to a function.

**Comment by jingshangwa** [comment]
Hi, yes, I am sure the arguments are available with correct file path, I have put full path of those files. However, all the arguments are mandotary to run the pubsub.py code, I was not able to find out which exact argument caused the error.

**Comment by khornberg** [comment]
I'm getting this as well by using the default `connect_device_pacakge.zip` that is offered in the `Connect One Device` form of the web console.

```
Traceback (most recent call last):
  File "/home/debian/aws-iot-device-sdk-python-v2/samples/mqtt5_pubsub.py", line 70, in <module>
    client = mqtt5_client_builder.mtls_from_path(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/awsiotvenv/lib/python3.11/site-packages/awsiot/mqtt5_client_builder.py", line 369, in mtls_from_path
    return _builder(tls_ctx_options, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/awsiotvenv/lib/python3.11/site-packages/awsiot/mqtt5_client_builder.py", line 347, in _builder
    tls_ctx = awscrt.io.ClientTlsContext(tls_ctx_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/debian/awsiotvenv/lib/python3.11/site-packages/awscrt/io.py", line 596, in __init__
    self._binding = _awscrt.client_tls_ctx_new(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 34 (AWS_ERROR_INVALID_ARGUMENT): An invalid argument was passed to a function.
```

The arguments being passed to `client_tls_ctx_new` are
```
128 
0
None 
b''
None 
b'-----BEGIN CERTIFICATE...END CERTIFICATE-----\n' 
b'-----BEGIN RSA PRIVATE KEY...END RSA PRIVATE KEY-----\n' 
None 
None 
True 
None 
None 
None 
None 
None 
None 
None 
None
```

**Comment by jingshangwa** [comment]
>

**Comment by jingshangwa** [comment]
I realize the root course is that "root-CA.crt" file downloaded in connect_device_pacakge.zip is empty.

you can solve the issue with the following command:

`$ curl https://www.amazontrust.com/repository/AmazonRootCA1.pem > CERT_FOLDER_LOCATION/root-CA.crt `

reference: https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html#server-authentication-certs

**Comment by khornberg** [comment]
thank you, that was the issue

**Comment by jmklix** [comment]
If you are using a new connection kit then it should work without any problems. It downloads it to the current directory which is where the sample is expecting it to be

```
# Check to see if root CA file exists, download if not
if [ ! -f ./root-CA.crt ]; then
  printf "\nDownloading AWS IoT Root CA certificate from AWS...\n"
  curl https://www.amazontrust.com/repository/AmazonRootCA1.pem > root-CA.crt
fi
```
